sudo: required
language: node_js
node_js:
- "14"
branches:
  except:
  - /^renovate\/.*$/
cache:
  directories:
  - '$HOME/.npm'
  - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: "tmorell"
install:
- npm install
script:
- npm run lint
- npm run build
- npm run test
- sonar-scanner
